name: Code Quality

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
    paths:
      - 'tesseract**'
      - '.github/workflows/code_quality.yml'
      - '.clang-tidy'
  schedule:
    - cron: '0 5 * * *'

jobs:
  ci:
    name: ${{ matrix.job_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_type: [clang-tidy, codecov]
        include:
          - job_type: clang-tidy
            env:
              TARGET_CMAKE_ARGS: "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_CLANG_TIDY=ON -DTESSERACT_ENABLE_TESTING=ON"
          - job_type: codecov
            env:
              TARGET_CMAKE_ARGS: "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_CODE_COVERAGE=ON -DTESSERACT_WARNINGS_AS_ERRORS=OFF"
    container:
      image: ghcr.io/tesseract-robotics/tesseract:focal-0.21
      env:
        CCACHE_DIR: "$GITHUB_WORKSPACE/${{ matrix.job_type }}/.ccache"
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: target_ws/src

      - name: Install Depends
        shell: bash
        run: |
          apt update
          apt upgrade -y
          apt install -y wget software-properties-common
          add-apt-repository ppa:levi-armstrong/tesseract-robotics
          apt install -y clang-tidy libompl-dev taskflow

      - name: Build and Tests
        uses: tesseract-robotics/colcon-action@v2
        with:
          before-script: source /opt/tesseract/install/setup.bash
          ccache-prefix: ${{ matrix.distro }}
          vcs-file: dependencies.repos
          run-tests: false
          upstream-args: --cmake-args -DCMAKE_BUILD_TYPE=Release
          target-path: target_ws/src
          target-args: --cmake-args ${{ matrix.env.TARGET_CMAKE_ARGS }}

      - name: Upload CodeCov Results
        shell: bash
        run: |
          if [[ "${{ matrix.job_type }}" == "codecov" ]]; then
            source $GITHUB_WORKSPACE/target_ws/install/setup.bash
            cd $GITHUB_WORKSPACE/target_ws
            colcon build --cmake-target ccov-all --packages-select tesseract_command_language tesseract_motion_planners tesseract_task_composer tesseract_time_parameterization
            bash <(curl -s https://codecov.io/bash) -t 6e7f085e-77c5-47fc-a4a9-c2dd5ef1d78d -s $GITHUB_WORKSPACE/target_ws/build -f *all-merged.info
          fi
