name: Mac OSX

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
    paths:
      - 'tesseract**'
      - '.github/workflows/mac.yml'
      - '**.repos'
  schedule:
    - cron: '0 5 * * *'
  release:
    types:
      - released

env:
  VCPKG_PKGS: >- 
    boost-dll boost-program-options
    boost-serialization boost-filesystem
    tinyxml2 console-bridge assimp
    urdfdom octomap orocos-kdl pcl
    gtest benchmark flann jsoncpp
    yaml-cpp eigen3
    openblas
    fcl ompl taskflow
    bullet3[multithreading,double-precision,rtti]
    ccd[double-precision] gperftools

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ws/src/tesseract_planning
    - uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.12'
    - name: brew
      run: |
        brew install libomp cmake automake autoconf libtool gcc ninja
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v5
      with:
        pkgs: >-
          ${{ env.VCPKG_PKGS }}
        triplet: x64-osx-dynamic-release
        extra-args: --clean-after-build --overlay-triplets=${{ github.workspace }}/ws/src/tesseract_planning/.github/workflows/vcpkg_triplets
        token: ${{ github.token }}
        cache-key: osx-x64-vcpkg
        revision: master
    - name: pip3
      run: |
        python3 -m pip install numpy setuptools wheel pytest delvewheel colcon-common-extensions vcstool
    - name: vcs import
      working-directory: ws/src
      run: vcs import --input tesseract_planning/.github/workflows/windows_dependencies.repos
    - name: colcon build
      working-directory: ws
      run: |
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$GITHUB_WORKSPACE/vcpkg/installed/x64-osx-dynamic-release/lib
        export CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/vcpkg/installed/x64-osx-dynamic-release

        colcon build --merge-install \
            --packages-ignore tesseract_examples trajopt_ifopt trajopt_sqp ifopt vhacd tesseract_python \
            --event-handlers console_cohesion+ \
            --cmake-force-configure \
            --cmake-args -GNinja -DCMAKE_BUILD_TYPE=Release \
            -DINSTALL_OMPL=OFF -DINSTALL_OMPL_TAG=master -DBUILD_IPOPT=OFF -DBUILD_SNOPT=OFF \
            -DBUILD_SHARED_LIBS=ON -DTESSERACT_ENABLE_EXAMPLES=OFF -DTESSERACT_BUILD_TRAJOPT_IFOPT=OFF \
            -DVCPKG_APPLOCAL_DEPS=OFF -DTESSERACT_ENABLE_TESTING=ON \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DOpenMP_CXX_INCLUDE_DIR=/usr/local/opt/libomp/include \
            -DOpenMP_C_INCLUDE_DIR=/usr/local/opt/libomp/include \
            -DOpenMP_CXX_LIB_NAMES=libomp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp" \
            -DOpenMP_C_LIB_NAMES=libomp -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp" \
            -DOpenMP_libomp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib \
            -Dtcmalloc_minimal_LIBRARY=${{ github.workspace }}/vcpkg/installed/x64-osx-dynamic-release/lib/libtcmalloc_minimal.dylib
    - name: colcon test
      working-directory: ws
      run: |
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$GITHUB_WORKSPACE/vcpkg/installed/x64-osx-dynamic-release/lib
        export CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/vcpkg/installed/x64-osx-dynamic-release

        colcon test --merge-install \
            --packages-ignore tesseract_examples trajopt_ifopt trajopt_sqp ifopt vhacd tesseract_python \
            --event-handlers console_cohesion+
    
